"""
Sample reviews data for the GMB CRM application.
This file contains realistic sample data that will be used to demonstrate
the dynamic dashboard statistics.
"""

# Sample reviews with customer data
SAMPLE_REVIEWS = [
    {
        'id': '1',
        'customer_name': 'Alice Johnson',
        'email': 'alice.j@gmail.com',
        'phone': '+1234567890',
        'company': 'Tech Corp',
        'rating': 5,
        'review_text': 'Outstanding customer service! The team went above and beyond to help us.',
        'review_date': '2024-01-15',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Thank you for your kind words! We\'re thrilled to have been of service.',
        'tags': ['VIP', 'High Rating', 'Satisfied'],
        'follow_up_required': False
    },
    {
        'id': '2',
        'customer_name': 'Bob Smith',
        'email': 'bob.smith@outlook.com',
        'phone': '+1234567891',
        'company': 'Local Business Inc.',
        'rating': 4,
        'review_text': 'Good product, delivery was a bit slow but overall happy with the purchase.',
        'review_date': '2024-01-14',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Thank you for your feedback! We\'ll work on improving our delivery times.',
        'tags': ['Delivery Issue'],
        'follow_up_required': False
    },
    {
        'id': '3',
        'customer_name': 'Carol Davis',
        'email': 'cdavis@gmail.com',
        'phone': '+1234567892',
        'company': 'Retail Solutions',
        'rating': 5,
        'review_text': 'Amazing experience! Will definitely recommend to others.',
        'review_date': '2024-01-13',
        'platform': 'Facebook',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'Recommendation'],
        'follow_up_required': True
    },
    {
        'id': '4',
        'customer_name': 'David Wilson',
        'email': 'dwilson@hotmail.com',
        'phone': '+1234567893',
        'company': 'Manufacturing LLC',
        'rating': 4,
        'review_text': 'Great service, just what we needed.',
        'review_date': '2024-01-12',
        'platform': 'Google',
        'status': 'responded',
        'response': 'We\'re glad we could meet your needs! Thank you for choosing us.',
        'tags': ['Satisfied'],
        'follow_up_required': False
    },
    {
        'id': '5',
        'customer_name': 'Emma Brown',
        'email': 'emma.brown@gmail.com',
        'phone': '+1234567894',
        'company': 'Creative Agency',
        'rating': 5,
        'review_text': 'Exceptional quality! Exceeded our expectations.',
        'review_date': '2024-01-11',
        'platform': 'Facebook',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'High Rating'],
        'follow_up_required': False
    },
    {
        'id': '6',
        'customer_name': 'Frank Thompson',
        'email': 'f.thompson@biz.com',
        'phone': '+1234567895',
        'company': 'Thompson Enterprises',
        'rating': 3,
        'review_text': 'Decent service but could be improved.',
        'review_date': '2024-01-10',
        'platform': 'Google',
        'status': 'responded',
        'response': 'We appreciate your honest feedback and are working on improvements.',
        'tags': ['Improvement Needed'],
        'follow_up_required': True
    },
    {
        'id': '7',
        'customer_name': 'Grace Lee',
        'email': 'grace.lee@gmail.com',
        'phone': '+1234567896',
        'company': 'Fashion Boutique',
        'rating': 5,
        'review_text': 'Fantastic experience! Love working with this team.',
        'review_date': '2024-01-09',
        'platform': 'Instagram',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'Satisfied'],
        'follow_up_required': False
    },
    {
        'id': '8',
        'customer_name': 'Henry Miller',
        'email': 'hmiller@corp.net',
        'phone': '+1234567897',
        'company': 'Miller Corp',
        'rating': 4,
        'review_text': 'Good quality products, reliable service.',
        'review_date': '2024-01-08',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Thank you for your continued trust in our services!',
        'tags': ['Regular Customer'],
        'follow_up_required': False
    },
    {
        'id': '9',
        'customer_name': 'Ivy Garcia',
        'email': 'ivy.g@gmail.com',
        'phone': '+1234567898',
        'company': 'Design Studio',
        'rating': 4,
        'review_text': 'Creative and professional team.',
        'review_date': '2024-01-07',
        'platform': 'Facebook',
        'status': 'pending',
        'response': None,
        'tags': ['Creative'],
        'follow_up_required': True
    },
    {
        'id': '10',
        'customer_name': 'Jack Rodriguez',
        'email': 'j.rodriguez@biz.com',
        'phone': '+1234567899',
        'company': 'Tech Solutions',
        'rating': 5,
        'review_text': 'Outstanding work! Highly recommended.',
        'review_date': '2024-01-06',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Thank you for the recommendation! It means a lot to us.',
        'tags': ['VIP', 'Recommendation'],
        'follow_up_required': False
    },
    {
        'id': '11',
        'customer_name': 'Karen Taylor',
        'email': 'k.taylor@gmail.com',
        'phone': '+1234567800',
        'company': 'Consulting LLC',
        'rating': 4,
        'review_text': 'Solid performance, good communication.',
        'review_date': '2024-01-05',
        'platform': 'LinkedIn',
        'status': 'pending',
        'response': None,
        'tags': ['Professional'],
        'follow_up_required': False
    },
    {
        'id': '12',
        'customer_name': 'Liam Anderson',
        'email': 'landerson@corp.com',
        'phone': '+1234567801',
        'company': 'Global Corp',
        'rating': 3,
        'review_text': 'Average experience, nothing special.',
        'review_date': '2024-01-04',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Thank you for your feedback. We\'ll strive to improve our service.',
        'tags': ['Improvement Needed'],
        'follow_up_required': True
    },
    {
        'id': '13',
        'customer_name': 'Maria Lopez',
        'email': 'maria.lopez@gmail.com',
        'phone': '+1234567802',
        'company': 'Retail Store',
        'rating': 5,
        'review_text': 'Excellent customer support! Very helpful.',
        'review_date': '2024-01-03',
        'platform': 'Facebook',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'Support'],
        'follow_up_required': False
    },
    {
        'id': '14',
        'customer_name': 'Nathan Kim',
        'email': 'n.kim@tech.net',
        'phone': '+1234567803',
        'company': 'Tech Innovations',
        'rating': 4,
        'review_text': 'Good product, fast delivery.',
        'review_date': '2024-01-02',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Glad you liked the fast delivery! Thank you for your business.',
        'tags': ['Fast Service'],
        'follow_up_required': False
    },
    {
        'id': '15',
        'customer_name': 'Olivia Chen',
        'email': 'olivia.chen@gmail.com',
        'phone': '+1234567804',
        'company': 'Design Agency',
        'rating': 5,
        'review_text': 'Creative and innovative solutions!',
        'review_date': '2024-01-01',
        'platform': 'Instagram',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'Creative', 'Innovation'],
        'follow_up_required': True
    },
    {
        'id': '16',
        'customer_name': 'Patrick White',
        'email': 'patrick.white@gmail.com',
        'phone': '+1234567805',
        'company': 'Media Group',
        'rating': 4,
        'review_text': 'Well-executed project, good results.',
        'review_date': '2023-12-31',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Thank you for your positive feedback! We\'re happy with the outcome too.',
        'tags': ['Project Success'],
        'follow_up_required': False
    },
    {
        'id': '17',
        'customer_name': 'Quinn Harris',
        'email': 'qharris@marketing.com',
        'phone': '+1234567806',
        'company': 'Digital Marketing',
        'rating': 5,
        'review_text': 'Superb quality and attention to detail!',
        'review_date': '2023-12-30',
        'platform': 'Facebook',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'Quality Focused'],
        'follow_up_required': True
    },
    {
        'id': '18',
        'customer_name': 'Rachel Scott',
        'email': 'r.scott@consulting.net',
        'phone': '+1234567807',
        'company': 'Strategic Consulting',
        'rating': 4,
        'review_text': 'Professional approach, valuable insights.',
        'review_date': '2023-12-29',
        'platform': 'LinkedIn',
        'status': 'responded',
        'response': 'We appreciate your recognition of our expertise!',
        'tags': ['Professional', 'Consulting'],
        'follow_up_required': False
    },
    {
        'id': '19',
        'customer_name': 'Samuel Green',
        'email': 'sam.green@build.com',
        'phone': '+1234567808',
        'company': 'Construction Co.',
        'rating': 3,
        'review_text': 'Service was average, could be better.',
        'review_date': '2023-12-28',
        'platform': 'Google',
        'status': 'pending',
        'response': None,
        'tags': ['Average Experience'],
        'follow_up_required': True
    },
    {
        'id': '20',
        'customer_name': 'Tina Martinez',
        'email': 'tina.martinez@gmail.com',
        'phone': '+1234567809',
        'company': 'Healthcare Solutions',
        'rating': 5,
        'review_text': 'Life-changing solutions! Grateful for the service.',
        'review_date': '2023-12-27',
        'platform': 'Facebook',
        'status': 'responded',
        'response': 'We\'re touched by your words! Thank you for trusting us with your care.',
        'tags': ['VIP', 'Grateful', 'Healthcare'],
        'follow_up_required': False
    },
    {
        'id': '21',
        'customer_name': 'Uma Patel',
        'email': 'uma.patel@finance.com',
        'phone': '+1234567810',
        'company': 'Financial Services',
        'rating': 4,
        'review_text': 'Reliable advice, trustworthy service.',
        'review_date': '2023-12-26',
        'platform': 'Google',
        'status': 'pending',
        'response': None,
        'tags': ['Reliable', 'Finance'],
        'follow_up_required': False
    },
    {
        'id': '22',
        'customer_name': 'Victor King',
        'email': 'v.king@logistics.net',
        'phone': '+1234567811',
        'company': 'Logistics Plus',
        'rating': 4,
        'review_text': 'Efficient delivery system, well-organized.',
        'review_date': '2023-12-25',
        'platform': 'Instagram',
        'status': 'responded',
        'response': 'Thank you for appreciating our logistics efficiency!',
        'tags': ['Efficient', 'Organized'],
        'follow_up_required': False
    },
    {
        'id': '23',
        'customer_name': 'Wendy Young',
        'email': 'wendy.young@gmail.com',
        'phone': '+1234567812',
        'company': 'Events Planning',
        'rating': 5,
        'review_text': 'Amazing event planning! Everything was perfect.',
        'review_date': '2023-12-24',
        'platform': 'Facebook',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'Perfect Experience', 'Events'],
        'follow_up_required': True
    },
    {
        'id': '24',
        'customer_name': 'Xavier Roberts',
        'email': 'x.roberts@security.biz',
        'phone': '+1234567813',
        'company': 'BioTech Security',
        'rating': 5,
        'review_text': 'Top-tier security solutions, highly secure.',
        'review_date': '2023-12-23',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Security is our top priority! Thank you for your trust.',
        'tags': ['VIP', 'Security', 'BioTech'],
        'follow_up_required': False
    },
    {
        'id': '25',
        'customer_name': 'Yara Ahmed',
        'email': 'yara.ahmed@design.org',
        'phone': '+1234567814',
        'company': 'Creative Designs',
        'rating': 4,
        'review_text': 'Innovative design work, impressed.',
        'review_date': '2023-12-22',
        'platform': 'Instagram',
        'status': 'pending',
        'response': None,
        'tags': ['Creative', 'Innovative'],
        'follow_up_required': True
    },
    {
        'id': '26',
        'customer_name': 'Zachary Moore',
        'email': 'z.moore@software.io',
        'phone': '+1234567815',
        'company': 'Software Solutions',
        'rating': 3,
        'review_text': 'Software works, but has some bugs.',
        'review_date': '2023-12-21',
        'platform': 'Google',
        'status': 'responded',
        'response': 'We\'re working to fix those bugs! Thank you for your patience.',
        'tags': ['Technical Issues'],
        'follow_up_required': True
    },
    {
        'id': '27',
        'customer_name': 'Amy Walker',
        'email': 'amy.walker@gmail.com',
        'phone': '+1234567816',
        'company': 'Retail Chain',
        'rating': 5,
        'review_text': 'Exceptional retail experience!',
        'review_date': '2023-12-20',
        'platform': 'Facebook',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'Retail'],
        'follow_up_required': False
    },
    {
        'id': '28',
        'customer_name': 'Brian Evans',
        'email': 'brian.evans@auto.com',
        'phone': '+1234567817',
        'company': 'Auto Services',
        'rating': 4,
        'review_text': 'Great car service, thorough work.',
        'review_date': '2023-12-19',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Thank you for your vehicle! Glad you\'re satisfied.',
        'tags': ['Thorough', 'Auto'],
        'follow_up_required': False
    },
    {
        'id': '29',
        'customer_name': 'Cathy Rivera',
        'email': 'cathy.rivera@hotel.biz',
        'phone': '+1234567818',
        'company': 'Luxury Hotels',
        'rating': 5,
        'review_text': 'Luxurious stay, amazing hospitality.',
        'review_date': '2023-12-18',
        'platform': 'Instagram',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'Luxury', 'Hospitality'],
        'follow_up_required': True
    },
    {
        'id': '30',
        'customer_name': 'Derek Long',
        'email': 'derek.long@fitness.net',
        'phone': '+1234567819',
        'company': 'Fitness Center',
        'rating': 4,
        'review_text': 'Good fitness programs, helpful trainers.',
        'review_date': '2023-12-17',
        'platform': 'Facebook',
        'status': 'responded',
        'response': 'Stay fit with us! Thank you for the feedback.',
        'tags': ['Fitness', 'Helpful'],
        'follow_up_required': False
    },
    {
        'id': '31',
        'customer_name': 'Elena Foster',
        'email': 'elena.foster@gmail.com',
        'phone': '+1234567820',
        'company': 'Education Services',
        'rating': 5,
        'review_text': 'Transformative educational experience!',
        'review_date': '2023-12-16',
        'platform': 'Google',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'Education'],
        'follow_up_required': False
    },
    {
        'id': '32',
        'customer_name': 'Felix Grant',
        'email': 'felix.grant@travel.com',
        'phone': '+1234567821',
        'company': 'Travel Agency',
        'rating': 4,
        'review_text': 'Smooth travel arrangements.',
        'review_date': '2023-12-15',
        'platform': 'Instagram',
        'status': 'responded',
        'response': 'Safe travels! Thank you for choosing our agency.',
        'tags': ['Travel', 'Smooth'],
        'follow_up_required': False
    },
    {
        'id': '33',
        'customer_name': 'Gabriela Perez',
        'email': 'gabriela.perez@food.biz',
        'phone': '+1234567822',
        'company': 'Food Services',
        'rating': 3,
        'review_text': 'Food was decent but service slow.',
        'review_date': '2023-12-14',
        'platform': 'Google',
        'status': 'pending',
        'response': None,
        'tags': ['Service Issue', 'Food'],
        'follow_up_required': True
    },
    {
        'id': '34',
        'customer_name': 'Helena Wright',
        'email': 'helena.wright@gmail.com',
        'phone': '+1234567823',
        'company': 'Art Gallery',
        'rating': 5,
        'review_text': 'Inspiring art collection!',
        'review_date': '2023-12-13',
        'platform': 'Facebook',
        'status': 'responded',
        'response': 'We\'re delighted you enjoyed our collection!',
        'tags': ['VIP', 'Art'],
        'follow_up_required': False
    },
    {
        'id': '35',
        'customer_name': 'Isaac Murphy',
        'email': 'isaac.murphy@legal.net',
        'phone': '+1234567824',
        'company': 'Legal Services',
        'rating': 4,
        'review_text': 'Trustworthy legal advice.',
        'review_date': '2023-12-12',
        'platform': 'LinkedIn',
        'status': 'pending',
        'response': None,
        'tags': ['Legal', 'Trustworthy'],
        'follow_up_required': True
    },
    {
        'id': '36',
        'customer_name': 'Julia Bailey',
        'email': 'julia.bailey@music.io',
        'phone': '+1234567825',
        'company': 'Music Studio',
        'rating': 5,
        'review_text': 'Outstanding music production!',
        'review_date': '2023-12-11',
        'platform': 'Instagram',
        'status': 'responded',
        'response': 'Making music together was a joy! Thank you.',
        'tags': ['VIP', 'Music'],
        'follow_up_required': False
    },
    {
        'id': '37',
        'customer_name': 'Kai Nakamura',
        'email': 'kai.nakamura@gmail.com',
        'phone': '+1234567826',
        'company': 'Tech Startups',
        'rating': 4,
        'review_text': 'Helpful startup guidance.',
        'review_date': '2023-12-10',
        'platform': 'Google',
        'status': 'pending',
        'response': None,
        'tags': ['Startup', 'Guidance'],
        'follow_up_required': False
    },
    {
        'id': '38',
        'customer_name': 'Luna Ortega',
        'email': 'luna.ortega@energy.biz',
        'phone': '+1234567827',
        'company': 'Clean Energy',
        'rating': 5,
        'review_text': 'Sustainable energy solutions!',
        'review_date': '2023-12-09',
        'platform': 'Facebook',
        'status': 'responded',
        'response': 'Building a sustainable future together!',
        'tags': ['VIP', 'Sustainability'],
        'follow_up_required': False
    },
    {
        'id': '39',
        'customer_name': 'Mason Reed',
        'email': 'mason.reed@photography.net',
        'phone': '+1234567828',
        'company': 'Photography Studio',
        'rating': 3,
        'review_text': 'Photography was okay, editing needed improvement.',
        'review_date': '2023-12-08',
        'platform': 'Instagram',
        'status': 'pending',
        'response': None,
        'tags': ['Improvement Needed', 'Photography'],
        'follow_up_required': True
    },
    {
        'id': '40',
        'customer_name': 'Natalie Sims',
        'email': 'natalie.sims@gmail.com',
        'phone': '+1234567829',
        'company': 'Real Estate',
        'rating': 4,
        'review_text': 'Smooth property transaction.',
        'review_date': '2023-12-07',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Welcome to your new home! So happy to help.',
        'tags': ['Real Estate', 'Smooth'],
        'follow_up_required': False
    },
    {
        'id': '41',
        'customer_name': 'Owen Hicks',
        'email': 'owen.hicks@accounting.biz',
        'phone': '+1234567830',
        'company': 'Accounting Firm',
        'rating': 5,
        'review_text': 'Meticulous accounting services!',
        'review_date': '2023-12-06',
        'platform': 'LinkedIn',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'Accounting'],
        'follow_up_required': True
    },
    {
        'id': '42',
        'customer_name': 'Paige Jenkins',
        'email': 'paige.jenkins@marketing.io',
        'phone': '+1234567831',
        'company': 'Marketing Agency',
        'rating': 4,
        'review_text': 'Effective marketing campaigns.',
        'review_date': '2023-12-05',
        'platform': 'Facebook',
        'status': 'responded',
        'response': 'Thank you for your business! Marketing success to you.',
        'tags': ['Marketing', 'Effective'],
        'follow_up_required': False
    },
    {
        'id': '43',
        'customer_name': 'Quincy Rogers',
        'email': 'quincy.rogers@gmail.com',
        'phone': '+1234567832',
        'company': 'E-commerce',
        'rating': 3,
        'review_text': 'Products good but packaging damaged.',
        'review_date': '2023-12-04',
        'platform': 'Google',
        'status': 'pending',
        'response': None,
        'tags': ['Packaging Issue'],
        'follow_up_required': True
    },
    {
        'id': '44',
        'customer_name': 'Riley Cooper',
        'email': 'riley.cooper@software.net',
        'phone': '+1234567833',
        'company': 'Software Corp',
        'rating': 5,
        'review_text': 'Intuitive software solutions!',
        'review_date': '2023-12-03',
        'platform': 'LinkedIn',
        'status': 'responded',
        'response': 'User experience is key! Thank you for the compliment.',
        'tags': ['VIP', 'UX'],
        'follow_up_required': False
    },
    {
        'id': '45',
        'customer_name': 'Stella Barnes',
        'email': 'stella.barnes@health.org',
        'phone': '+1234567834',
        'company': 'Health Clinic',
        'rating': 4,
        'review_text': 'Caring healthcare professionals.',
        'review_date': '2023-12-02',
        'platform': 'Facebook',
        'status': 'pending',
        'response': None,
        'tags': ['Healthcare', 'Caring'],
        'follow_up_required': False
    },
    {
        'id': '46',
        'customer_name': 'Theo Collins',
        'email': 'theo.collins@construction.io',
        'phone': '+1234567835',
        'company': 'Construction LLC',
        'rating': 5,
        'review_text': 'Expert construction work!',
        'review_date': '2023-12-01',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Building dreams together! Thank you for trusting us.',
        'tags': ['VIP', 'Construction'],
        'follow_up_required': False
    },
    {
        'id': '47',
        'customer_name': 'Ursula Diaz',
        'email': 'ursula.diaz@gmail.com',
        'phone': '+1234567836',
        'company': 'Non-profit Org',
        'rating': 4,
        'review_text': 'Meaningful charitable work.',
        'review_date': '2023-11-30',
        'platform': 'Instagram',
        'status': 'pending',
        'response': None,
        'tags': ['Charity', 'Meaningful'],
        'follow_up_required': True
    },
    {
        'id': '48',
        'customer_name': 'Vincent Ellis',
        'email': 'vincent.ellis@finance.org',
        'phone': '+1234567837',
        'company': 'Investment Group',
        'rating': 3,
        'review_text': 'Financial planning adequate but not outstanding.',
        'review_date': '2023-11-29',
        'platform': 'LinkedIn',
        'status': 'responded',
        'response': 'We\'ll continue to improve our financial services.',
        'tags': ['Finance', 'Adequate'],
        'follow_up_required': True
    },
    {
        'id': '49',
        'customer_name': 'Wendy Foster',
        'email': 'wendy.foster@events.biz',
        'phone': '+1234567838',
        'company': 'Event Planning',
        'rating': 5,
        'review_text': 'Unforgettable event experiences!',
        'review_date': '2023-11-28',
        'platform': 'Facebook',
        'status': 'pending',
        'response': None,
        'tags': ['VIP', 'Events'],
        'follow_up_required': False
    },
    {
        'id': '50',
        'customer_name': 'Xander Gordon',
        'email': 'xander.gordon@gmail.com',
        'phone': '+1234567839',
        'company': 'Research Lab',
        'rating': 5,
        'review_text': 'Groundbreaking research collaboration!',
        'review_date': '2023-11-27',
        'platform': 'Google',
        'status': 'responded',
        'response': 'Advancing science together! Very grateful for the partnership.',
        'tags': ['VIP', 'Research'],
        'follow_up_required': False
    }
]

def get_reviews():
    """Return all sample reviews."""
    return SAMPLE_REVIEWS

def calculate_dashboard_stats(reviews=None):
    """Calculate dashboard statistics based on reviews."""
    if reviews is None:
        reviews = SAMPLE_REVIEWS

    total_reviews = len(reviews)
    if total_reviews == 0:
        return {
            'total_customers': 0,
            'vip_customers': 0,
            'avg_rating': 0.0,
            'follow_up_needed': 0
        }

    total_customers = total_reviews  # Each review represents a customer interaction
    vip_customers = len([r for r in reviews if 'VIP' in r['tags']])
    avg_rating = sum(r['rating'] for r in reviews) / total_reviews
    follow_up_needed = len([r for r in reviews if r['follow_up_required']])

    return {
        'total_customers': total_customers,
        'vip_customers': vip_customers,
        'avg_rating': round(avg_rating, 2),
        'follow_up_needed': follow_up_needed
    }

if __name__ == '__main__':
    # Print some statistics when run directly
    stats = calculate_dashboard_stats()
    print("Dashboard Statistics:")
    print(f"Total Customers: {stats['total_customers']}")
    print(f"VIP Customers: {stats['vip_customers']}")
    print(f"Average Rating: {stats['avg_rating']}")
    print(f"Follow-up Needed: {stats['follow_up_needed']}")
